extends: substitution
message: "Prefer '%s' over '%s'."
level: warning
ignorecase: true
action:
  name: replace
swap:
  adaptor: adapter
  administrate: administer
  afterwards: afterward
  alphabetic: alphabetical
  alphanumerical: alphanumeric
  anti-aliasing: antialiasing
  anti-malware: antimalware
  anti-spyware: antispyware
  anti-virus: antivirus
  appendixes: appendices
  assembler: assembly language
  eb: EB
  gb: GB
  gbps: Gbps
  kb: KB
  keypress: keystroke
  mb: MB
  pb: PB
  tb: TB
  zb: ZB
  viz: namely
  ergo: therefore
