extends: existence
message: "Use percantage unless including a numeric value. Then use percent."
link: https://docs.microsoft.com/en-us/style-guide/numbers
nonword: true
level: error
tokens:
  - '\b[a-zA-z]+\spercent\b'
