agentName: apache-flink
agentType: integration
title: 'Apache Flink monitoring integration'
metaDescription: 'Install the Apache Flink integration'
introFilePath: 'src/install/apache-flink/intro.mdx'
redirects:
    - /docs/infrastructure/prometheus-integrations/install-configure-openmetrics/install-apache-flink/
    - /docs/infrastructure/host-integrations/host-integrations-list/install-apache-flink/
appInfo: 
  - optionType: dropdown1
    label: ''
    placeholder: 'Select your environment'
    options: 
      - value: 'linux'
        displayName: 'Linux'
        logo: 'linux'
      - value: 'windows'
        displayName: 'Windows'
        logo: 'windows'

steps:
  - filePath: 'src/install/apache-flink/install-infra.mdx'
  - filePath: 'src/install/apache-flink/configure-apache.mdx'
  - filePath: 'src/install/apache-flink/check-metrics.mdx'   
  - filePath: 'src/install/apache-flink/configure-prometheus-apache.mdx'        
  - filePath: 'src/install/apache-flink/configure-logging-apache.mdx'      
  - filePath: 'src/install/apache-flink/find-data.mdx'
whatsNextFilePath: 'src/install/apache-flink/whatsNext.mdx'
