version: "3.9"

services:
    postgres:
        image: postgres:14-alpine
        restart: always
        environment:
            POSTGRES_PASSWORD: root
            POSTGRES_USER: root
            POSTGRES_DB: translations
        ports:
            - 5432:5432
        volumes:
            - postgres:/var/lib/postgresql/data
    pgadmin:
        image: dpage/pgadmin4:6.2
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
            PGADMIN_DEFAULT_PASSWORD: password
            PGADMIN_LISTEN_PORT: 80
        ports:
            - 15432:80
        volumes:
            - pgadmin:/var/lib/pgadmin
        depends_on:
            - postgres
    migration:
        build:
          context: .
          dockerfile: ./Dockerfile
        depends_on:
            - "postgres"

volumes:
    postgres:
    pgadmin:
